// Code generated by mockery v2.16.0. DO NOT EDIT.

package shortener

import mock "github.com/stretchr/testify/mock"

// MockShortener is an autogenerated mock type for the Shortener type
type MockShortener struct {
	mock.Mock
}

// Short provides a mock function with given fields: link
func (_m *MockShortener) Short(link string) string {
	ret := _m.Called(link)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(link)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewMockShortener interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockShortener creates a new instance of MockShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockShortener(t mockConstructorTestingTNewMockShortener) *MockShortener {
	mock := &MockShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
