// Code generated by mockery v2.16.0. DO NOT EDIT.

package server

import mock "github.com/stretchr/testify/mock"

// mockHandlerShortener is an autogenerated mock type for the handlerShortener type
type mockHandlerShortener struct {
	mock.Mock
}

// Short provides a mock function with given fields: link
func (_m *mockHandlerShortener) Short(link string) string {
	ret := _m.Called(link)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(link)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTnewMockHandlerShortener interface {
	mock.TestingT
	Cleanup(func())
}

// newMockHandlerShortener creates a new instance of mockHandlerShortener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockHandlerShortener(t mockConstructorTestingTnewMockHandlerShortener) *mockHandlerShortener {
	mock := &mockHandlerShortener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
